class BaseViewHints < Hobo::ViewHints
	# NOTE: there can only be a single call to field_help, field_names etc.
	# Otherwise only the last call of each will have any effect.
	
	field_names :seqdata => "Sequengfgfce"
	
	field_help (:seqdata => "The sequence residues entered as standard IUPAC codes.
			Whitespace will be stripped before saving.",
		:identifier => "An id for this record. When combined with the source, it
			should form a globallty unique name. If one is not given, it will be
			autogenerated.",
		:source => "The originating authority for this record. It should
		either be a single definitive name (e.g. 'genbank') or reverse-url format
		(e.g. 'uk.ac.imperial.bio').",
		:title => "A user-friendly name for the record that will appear
		in all listings.",
		:description => "A suumary of the record and its content.",
		:foo => "hwtw is this")

	field_help['foo'] = "hata"

end

pp "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS"
pp BaseViewHints.field_names