
class BiosequenceHints < ExtendedViewHints

	field_names ({
		:seqdata => "Sequence",
	})
	
	field_help ({
		:seqdata => "The sequence residues entered as standard IUPAC codes.
			Whitespace will be stripped before saving.",
		:identifier => "An id for this record. When combined with the source, it
			should form a globally unique name. If one is not given, it will be
			autogenerated.",
		:source => "The originating authority for this record. It should either be
			a single definitive name (e.g. 'genbank') or reverse-url format
			(e.g. 'uk.ac.imperial.bio').",
		:title => "A user-friendly name for the record that will appear
			in all listings.",
		:description => "A summary of the record and its content.",
	})
	
	rows ({
		:description => 5,
		:seqdata => 7,
	})
	
	children :bioseqfeatures, :bioseqcollections

	set_defaults	
end
